apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: eshope
  labels:
    app.kubernetes.io/name: backend-api
    app.kubernetes.io/part-of: eshope-platform
spec:
  type: ClusterIP
  selector:
    app: backend-api
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
