apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: eshope
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: eshope-platform
type: Opaque
stringData:
  POSTGRES_DB: eshopedb
  POSTGRES_USER: eshopeuser
  POSTGRES_PASSWORD: change-me-in-prod
