apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: eshope
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: eshope-platform
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
