version: '3.9'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: eshopedb
      POSTGRES_USER: eshopeuser
      POSTGRES_PASSWORD: change-me-in-prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  backend:
    build: ./app/backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_DB: eshopedb
      POSTGRES_USER: eshopeuser
      POSTGRES_PASSWORD: change-me-in-prod
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  frontend:
    build: ./app/frontend
    environment:
      API_URL: http://localhost:5000
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
