apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backend-api   # ✅ correct label
  namespaceSelector:
    matchNames:
      - eshope
  endpoints:
  - port: http   # ⚠️ see note below
    path: /metrics
    interval: 15s
