apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    matchNames:
      - eshope   # your app namespace
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
