apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: eshope
  labels:
    app.kubernetes.io/part-of: eshope-platform
data:
  API_URL: http://backend-service:5000
  DB_HOST: postgres-service
  DB_PORT: "5432"
