apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: ${TENANT}
spec:
  limits:
  - type: Container
    max:
      cpu: "1"
      memory: 2Gi
    default:
      cpu: 500m
      memory: 512Mi
